// Parses the pages generated by the Jenkins "Cucumber Reports" plugin (cucumber-reporting):
//   overview-failures.html -> one <div class="element"> per failed scenario
//   overview-features.html -> totals in the <tfoot> of the features table
// Produces the same failure/summary shapes as cucumberParser so grouping and export work unchanged.

const { MalformedReportError } = require('../utils/errors');

const ELEMENT_START = '<div class="element">';
const NON_PASSING = new Set(['failed', 'undefined', 'pending', 'ambiguous']);
const GROUP_KEYWORDS = new Set(['Steps', 'Hooks']);

// <div class="brief [step-name-X ]status"> <span class="keyword ...">KW</span> <span class="[location ]name">NAME ...
const BRIEF_PATTERN =
  /<div class="brief (?:step-name-\S+ )?(\w+)">\s*<span class="keyword indention">([\s\S]*?)<\/span>\s*<span class="(?:location )?name">([\s\S]*?)(?=\s*<span class="lead-duration|\s*<i class="chevron|\s*<\/div>)/g;

function decodeEntities(text) {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&');
}

function toText(html) {
  return decodeEntities(html.replace(/<[^>]*>/g, '')).replace(/\s+/g, ' ').trim();
}

function parseBriefs(elementHtml) {
  return Array.from(elementHtml.matchAll(BRIEF_PATTERN), (m) => ({
    status: m[1],
    keyword: toText(m[2]),
    name: toText(m[3]),
    index: m.index,
  }));
}

// The error for a step/hook is the <pre> inside the .message block that follows its brief,
// before the next brief starts.
function errorMessageBetween(elementHtml, start, end) {
  const section = elementHtml.slice(start, end);
  const messageIdx = section.indexOf('<div class="message indention">');
  if (messageIdx === -1) return '';
  const pre = section.slice(messageIdx).match(/<pre>([\s\S]*?)<\/pre>/);
  return pre ? decodeEntities(pre[1]).trim() : '';
}

function failedStepLabel(brief) {
  if (brief.keyword === 'Before' || brief.keyword === 'After') return `${brief.keyword} Hook`;
  return `${brief.keyword} ${brief.name}`.trim() || '(unnamed step)';
}

// Screenshots attached to the scenario (scenario.attach / embed), e.g. embeddings/embedding_-123.png
function extractScreenshots(elementHtml, reportUrl) {
  const paths = Array.from(elementHtml.matchAll(/<img src="(embeddings\/[^"]+)"/g), (m) => decodeEntities(m[1]));
  return [...new Set(paths)].map((p) => `${reportUrl}${p}`);
}

function parseElement(elementHtml, reportUrl) {
  const featureMatch = elementHtml.match(/<b>Feature:<\/b>\s*<a[^>]*>([\s\S]*?)<\/a>/);
  const tagsMatch = elementHtml.match(/<div class="tags indention">([\s\S]*?)<\/div>/);
  const tags = tagsMatch ? Array.from(tagsMatch[1].matchAll(/<a[^>]*>([\s\S]*?)<\/a>/g), (m) => toText(m[1])) : [];

  const briefs = parseBriefs(elementHtml);
  const [scenarioBrief, ...inner] = briefs;
  const steps = inner.filter((b) => !GROUP_KEYWORDS.has(b.keyword));
  const culpritIdx = steps.findIndex((b) => NON_PASSING.has(b.status));
  const culprit = steps[culpritIdx];

  let errorMessage = '';
  if (culprit) {
    const next = steps[culpritIdx + 1];
    errorMessage = errorMessageBetween(elementHtml, culprit.index, next ? next.index : elementHtml.length);
  }

  const status = culprit ? (culprit.status === 'ambiguous' ? 'failed' : culprit.status) : 'failed';

  return {
    feature: featureMatch ? toText(featureMatch[1]) : '(unnamed feature)',
    scenario: (scenarioBrief && scenarioBrief.name) || '(unnamed scenario)',
    failedStep: culprit ? failedStepLabel(culprit) : '(unknown step)',
    errorMessage,
    status,
    tags,
    screenshots: extractScreenshots(elementHtml, reportUrl),
  };
}

// reportUrl: the cucumber-html-reports/ folder URL, used to make screenshot links absolute.
function extractFailuresFromHtml(failuresHtml, reportUrl = '') {
  if (!failuresHtml || !failuresHtml.includes('Failures Overview')) {
    throw new MalformedReportError('The Cucumber HTML failures page does not look like a Cucumber Reports "Failures Overview".');
  }
  return failuresHtml
    .split(ELEMENT_START)
    .slice(1)
    .map((elementHtml) => parseElement(elementHtml, reportUrl));
}

// Feature table footer columns: '', steps passed, failed, skipped, pending, undefined, total,
// scenarios passed, failed, total, duration, features ...
function getSummaryFromHtml(featuresHtml, failures) {
  const footer = (featuresHtml || '').match(/<tfoot[^>]*>\s*<tr>([\s\S]*?)<\/tr>/);
  if (!footer) {
    throw new MalformedReportError('Could not find the totals row in the Cucumber HTML features overview.');
  }
  const cells = Array.from(footer[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g), (m) => toText(m[1]));
  const scenariosPassed = parseInt(cells[7], 10);
  const scenariosTotal = parseInt(cells[9], 10);
  if (Number.isNaN(scenariosPassed) || Number.isNaN(scenariosTotal)) {
    throw new MalformedReportError('Could not read scenario totals from the Cucumber HTML features overview.');
  }

  const countStatus = (s) => failures.filter((f) => f.status === s).length;
  return {
    total: scenariosTotal,
    passed: scenariosPassed,
    failed: countStatus('failed'),
    undefined: countStatus('undefined'),
    pending: countStatus('pending'),
  };
}

module.exports = { extractFailuresFromHtml, getSummaryFromHtml, decodeEntities };
